### ISSUE TITLE
How can I get pdf of label using this library?

### ISSUE THREAD

**Issue by Kedar782** [dsandor/dymojs#23]
I want to get the PDF of the label.
When I'm using the renderLabel and print function I'm getting the timeout error.
I'm using this library in the SvelteKit project.
Anybody here has any idea how can I fix it?

**Comment by dsandor** [comment]
Hi @Kedar782. This library does not generate PDFs. This project is a JavaScript based abstraction layer for the DymoLabelWriter API. This library generates XML requests to that library in order for the printer to print. The Dymo printers do not print PDF they take positional commands via an API.  If you wish to generate PDFs there are other libraries you can use for that purpose. I suggest trying a search of github as a good starting point.
